name: Deploy front-gestao-de-ativos.
on:
  push:
    branches:
      - dev
      - master
jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Copy env (dev)
      if: github.ref == 'refs/heads/dev'
      run: php -r "copy('app/.env.dev', 'app/.env');"
    - name: Copy env (master)
      if: github.ref == 'refs/heads/master'
      run: php -r "copy('app/.env.production', 'app/.env');"
    - name: Remove envs
      run: |
          php -r "unlink('app/.env.dev');"
          php -r "unlink('app/.env.production');"
    - uses: google-github-actions/setup-gcloud@v0
      with:
        service_account_email: ${{ secrets.GCP_EMAIL }}
        service_account_key: ${{ secrets.GCP_CREDENTIALS }}
    - name: Configure Docker
      run: |
          gcloud auth configure-docker
    - name: Build & Publish - staging
      if: github.ref == 'refs/heads/dev'
      run: |
          gcloud config set project ${{ secrets.GCP_PROJECT }}
          gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.GCP_APPLICATION }}:staging-${{ github.sha }}
          gcloud config set run/region us-central1
          gcloud container clusters get-credentials sjcc-staging --zone us-central1 --project ${{ secrets.GCP_PROJECT }}
    - name: Build & Publish - production
      if: github.ref == 'refs/heads/master'
      run: |
          gcloud config set project ${{ secrets.GCP_PROJECT }}
          gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.GCP_APPLICATION }}:production-${{ github.sha }}
          gcloud config set run/region us-central1
          gcloud container clusters get-credentials sjcc-production --zone us-central1 --project ${{ secrets.GCP_PROJECT }}
    - uses: azure/setup-helm@v1
      id: install
    - name: Install or Upgrade - staging
      if: github.ref == 'refs/heads/dev'
      run: helm upgrade --install ${{ secrets.GCP_APPLICATION }} Chart/ --set app.version=${{ github.sha }} --set app.enviroment=staging --set app.host=gas.sjcc.dev --set app.rCpu=100m --set app.rMemory=128Mi --set app.lCpu=150m --set app.lMemory=256Mi --set app.minReplicas=1 --set app.maxReplicas=3 --namespace produtos-internos --create-namespace
    - name: Install or Upgrade - production
      if: github.ref == 'refs/heads/master'
      run: helm upgrade --install ${{ secrets.GCP_APPLICATION }} Chart/ --set app.version=${{ github.sha }} --set app.enviroment=production --set app.host=gas.sjcc.com.br --set app.rCpu=150m --set app.rMemory=256Mi --set app.lCpu=300m --set app.lMemory=512Mi --set app.minReplicas=1 --set app.maxReplicas=3 --namespace produtos-internos --create-namespace
    - name: Discord  
      uses: sarisia/actions-status-discord@v1
      if: always()
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
